### ISSUE TITLE
Cannot run `realtime` on `localhost` 🤷‍♂️ 

### ISSUE THREAD

**Issue by nelsonic** [4kd/realtime#1]
Error running on `localhost`:

Ran:
```sh
mix setup
```

Got:
```sh
16:31:18.492 [info] alter table tenants

16:31:18.493 [info] == Migrated 20230110180046 in 0.0s
16:31:18.771 [info] Elixir.Realtime.SignalHandler is being initialized... file=lib/realtime/signal_handler.ex pid=<0.60.0>
16:31:18.772 [notice] Application realtime exited: exited in: Realtime.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in String.split/3
            (elixir 1.14.1) lib/string.ex:479: String.split(nil, "-", [parts: 2])
            (realtime 2.1.1) lib/realtime/helpers.ex:100: Realtime.Helpers.short_node_id/0
            (realtime 2.1.1) lib/realtime/monitoring/prom_ex.ex:145: Realtime.PromEx.set_metrics_tags/0
            (realtime 2.1.1) lib/realtime/application.ex:33: Realtime.Application.start/2
            (kernel 8.5.1) application_master.erl:293: :application_master.start_it_old/4 file=application_controller.erl pid=<0.44.0>
16:31:18.788 [notice] Application excoveralls exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.788 [notice] Application tools exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application cachex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application sleeplocks exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application jumper exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application eternal exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application unsafe exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application timex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.794 [notice] Application combine exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.795 [notice] Application tzdata exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.795 [notice] Application benchee exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.795 [notice] Application statistex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.795 [notice] Application deep_merge exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application syn exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application httpoison exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application hackney exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application metrics exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application ssl_verify_fun exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application parse_trans exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application syntax_tools exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application certifi exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application mimerl exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application idna exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.796 [notice] Application unicode_util_compat exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application logflare_logger_backend exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application logflare_api_client exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application tesla exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application etso exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application bertex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application typed_struct exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application mint_web_socket exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application recon exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application phoenix_swagger exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application ex_json_schema exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.797 [notice] Application joken exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.798 [notice] Application jose exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.798 [notice] Application uuid exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.798 [notice] Application libcluster exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.798 [notice] Application gettext exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.798 [notice] Application tailwind exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application esbuild exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application phoenix_live_dashboard exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application phoenix_live_reload exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application file_system exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application phoenix_live_view exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application phoenix_html exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.799 [notice] Application ecto_psql_extras exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.800 [notice] Application table_rex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.800 [notice] Application phoenix_ecto exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.800 [notice] Application phoenix exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.800 [notice] Application phoenix_view exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.800 [notice] Application phoenix_pubsub exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.801 [notice] Application os_mon exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.801 [notice] Application sasl exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.801 [notice] Application prom_ex exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application plug_cowboy exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application cowboy_telemetry exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application cowboy exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application ranch exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application cowlib exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.802 [notice] Application plug exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application plug_crypto exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application mime exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application telemetry_metrics_prometheus_core exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application telemetry_metrics exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application telemetry_poller exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application finch exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application nimble_options exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application nimble_pool exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.803 [notice] Application castore exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.804 [notice] Application mint exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.804 [notice] Application hpax exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.804 [notice] Application jason exited: :stopped file=application_controller.erl pid=<0.44.0>
16:31:18.804 [notice] Application runtime_tools exited: :stopped file=application_controller.erl pid=<0.44.0>
Error writing to pipe: Broken pipe
** (Mix) Could not start application realtime: exited in: Realtime.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in String.split/3
            (elixir 1.14.1) lib/string.ex:479: String.split(nil, "-", [parts: 2])
            (realtime 2.1.1) lib/realtime/helpers.ex:100: Realtime.Helpers.short_node_id/0
            (realtime 2.1.1) lib/realtime/monitoring/prom_ex.ex:145: Realtime.PromEx.set_metrics_tags/0
            (realtime 2.1.1) lib/realtime/application.ex:33: Realtime.Application.start/2
            (kernel 8.5.1) application_master.erl:293: :application_master.start_it_old/4
n@mbp16 realtime % [os_mon] cpu supervisor port (cpu_sup): Error writing to Erlang
```

Tried to:
```sh
mix ecto.reset
```

Get:
```sh
** (Mix) The database for Realtime.Repo couldn't be dropped: ERROR 55006 (object_in_use) cannot drop the currently open database
```

```sh
mix test
** (MatchError) no match of right hand side value: {:error, :rollback}
    priv/repo/seeds_after_migration.exs:40: (file)
    (elixir 1.14.1) lib/code.ex:1245: Code.require_file/2
    (mix 1.14.1) lib/mix/tasks/run.ex:144: Mix.Tasks.Run.run/5
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
```

# 🤦‍♂️

**Comment by nelsonic** [comment]
```sh
rm -rf realtime
```

This is a non-starter. Literally.
